services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      # Rabbitmq instance
      - '5672:5672'
      # Web interface
      - '15672:15672'
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    ports:
      - "3310:3310"
    restart: unless-stopped
    volumes:
      - clam:/var/lib/clamav
    healthcheck:
      test: ["CMD", "./check.sh"]
      interval: 60s
      retries: 3
      start_period: 120s
    
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__Postgres=User ID=postgres;Password=Qjf39JK2Njuw194;Server=database;Port=5432;Database=eShopClothingIdentity;Pooling=true;
  #     - Redis__Connection=redis:6379
  #   depends_on:
  #     - database
  #     - redis

  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"

#   database:
#     image: "postgres:latest"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: Qjf39JK2Njuw194
#       POSTGRES_DB: eShopClothingIdentity
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

volumes:
  clam: